import { createFileRoute, Link } from "@tanstack/react-router";
import { Target, Users, Lock, ShieldCheck, Stethoscope, Download, Cpu } from "lucide-react";
import { MarketingLayout } from "@/components/marketing/MarketingLayout";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [
      { title: "Architecture & Philosophy — InsightForge Healthcare & Education RAG" },
      {
        name: "description",
        content:
          "Cited RAG document intelligence for medical guidelines, PubMed studies, and university curricula with zero data leakage.",
      },
    ],
  }),
  component: AboutPage,
});

const pillars = [
  {
    icon: Stethoscope,
    title: "Clinical & Evidence Rigor",
    body: "Medical answers must be grounded in verified guidelines and clinical trial papers with explicit page and paragraph citations.",
    badge: "EVIDENCE CITED",
  },
  {
    icon: Users,
    title: "Designed for Clinicians & Educators",
    body: "Doctors, medical researchers, professors, and students share a unified RAG document context with multi-user isolation.",
    badge: "MULTI-ROLE RAG",
  },
  {
    icon: Lock,
    title: "100% HIPAA & FERPA Privacy",
    body: "Local FAISS vector store running directly on disk with zero third-party cloud data leakage or external tracking.",
    badge: "AIR-GAPPED FAISS",
  },
];

const sections = [
  {
    icon: Target,
    eyebrow: "OUR MISSION",
    title: "Empowering Healthcare & Education with Cited RAG AI.",
    body: "Medical guidelines and academic literature expand by thousands of pages daily. We built InsightForge Health & Edu RAG to instantly retrieve precise clinical evidence from 100-page PDFs and EMR datasets.",
  },
  {
    icon: ShieldCheck,
    eyebrow: "GROUND-TRUTH PHILOSOPHY",
    title: "Zero hallucination. Page & paragraph citations.",
    body: "Every clinical summary generated by our RAG pipeline cites exact vector chunks retrieved from PubMed PDFs or FDA drug protocols.",
  },
  {
    icon: Cpu,
    eyebrow: "DATA PRIVACY & SOVEREIGNTY",
    title: "Air-gapped local FAISS vector architecture.",
    body: "Sentence-transformers embeddings and vector calculations run locally on your institution's infrastructure, guaranteeing total patient and student privacy.",
  },
];

function AboutPage() {
  return (
    <MarketingLayout>
      {/* PAGE HERO HEADER */}
      <section className="bg-[#000000] py-14 md:py-20 border-b border-[rgba(178,182,189,0.12)] text-white">
        <div className="mx-auto max-w-4xl px-6 text-center space-y-4">
          <div className="eyebrow-hashicorp text-[#844fba] inline-block px-3 py-1 bg-[#844fba]/10 rounded-full border border-[#844fba]/20">
            HEALTHCARE & EDUCATION MISSION
          </div>
          <h1 className="display-hashicorp-lg text-white">
            Trustworthy, cited RAG AI for medicine & learning.
          </h1>
          <p className="body-hashicorp-lg text-[#b2b6bd] max-w-2xl mx-auto">
            Dense FAISS vector document retrieval across clinical guidelines and course materials running 100% locally on your computer.
          </p>
        </div>
      </section>

      {/* CORE PILLARS GRID */}
      <section className="bg-[#000000] py-16 md:py-24 border-b border-[rgba(178,182,189,0.12)] text-white">
        <div className="mx-auto max-w-6xl px-8">
          <div className="grid gap-6 md:grid-cols-3">
            {pillars.map((p) => {
              const Icon = p.icon;
              return (
                <div
                  key={p.title}
                  className="hashicorp-card p-6 flex flex-col justify-between"
                >
                  <div className="space-y-4">
                    <div className="flex items-center justify-between border-b border-[rgba(178,182,189,0.12)] pb-4">
                      <div className="flex h-10 w-10 items-center justify-center rounded-md bg-[#242424] text-[#844fba]">
                        <Icon className="h-5 w-5" />
                      </div>
                      <span className="product-pill text-[11px]">{p.badge}</span>
                    </div>
                    <h3 className="headline-hashicorp text-white text-lg">{p.title}</h3>
                    <p className="body-hashicorp text-sm text-[#b2b6bd]">{p.body}</p>
                  </div>

                  <div className="mt-6 pt-3 border-t border-[rgba(178,182,189,0.12)] flex items-center justify-between text-xs font-mono text-[#00c9a7]">
                    <span>ARCHITECTURE PILLAR</span>
                    <ShieldCheck className="h-4 w-4" />
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* DETAILED PHILOSOPHY & ARCHITECTURE SECTIONS */}
      <section className="bg-[#000000] py-16 md:py-24 border-b border-[rgba(178,182,189,0.12)] text-white">
        <div className="mx-auto max-w-5xl px-8 flex flex-col gap-10">
          {sections.map((s) => {
            const Icon = s.icon;
            return (
              <div
                key={s.title}
                className="hashicorp-card p-8 grid md:grid-cols-12 gap-6 items-start"
              >
                <div className="md:col-span-2 flex h-12 w-12 items-center justify-center rounded-md bg-[#242424] text-[#844fba]">
                  <Icon className="h-6 w-6" />
                </div>
                <div className="md:col-span-10 space-y-2">
                  <div className="eyebrow-hashicorp text-[#844fba]">{s.eyebrow}</div>
                  <h2 className="headline-hashicorp text-white text-2xl">{s.title}</h2>
                  <p className="body-hashicorp text-sm text-[#b2b6bd]">{s.body}</p>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* CALL TO ACTION BANNER - DIRECT DESKTOP EXE DOWNLOAD */}
      <section className="bg-[#000000] py-16 md:py-20 text-white">
        <div className="mx-auto max-w-4xl px-8 text-center">
          <div className="hashicorp-card p-10 md:p-12 text-center space-y-5 border-[rgba(178,182,189,0.2)] bg-[#141414]">
            <div className="eyebrow-hashicorp text-[#844fba]">SYSTEM ARCHITECTURE READY</div>
            <h2 className="headline-hashicorp text-2xl sm:text-3xl text-white">
              Run Local RAG On Your Computer's Hardware.
            </h2>
            <p className="body-hashicorp text-sm text-[#b2b6bd] max-w-xl mx-auto">
              Download the standalone executable to process PubMed PDFs and lecture syllabi 100% offline on your machine.
            </p>
            <div className="pt-2">
              <a
                href="/downloads/InsightForge-Desktop.exe"
                download="InsightForge-Desktop.exe"
                className="btn-hashicorp-primary flex items-center justify-center gap-2 max-w-md mx-auto"
              >
                <Download className="w-4 h-4 text-black" />
                <span>Download Standalone Desktop App (.exe)</span>
              </a>
            </div>
          </div>
        </div>
      </section>
    </MarketingLayout>
  );
}