/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUploadRouteImport } from './routes/app.upload'
import { Route as AppQueryRouteImport } from './routes/app.query'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAnomaliesRouteImport } from './routes/app.anomalies'
import { Route as AppAnomaliesIdRouteImport } from './routes/app.anomalies.$id'

const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppQueryRoute = AppQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnomaliesRoute = AppAnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => AppRoute,
} as any)
const AppAnomaliesIdRoute = AppAnomaliesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAnomaliesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/app/anomalies': typeof AppAnomaliesRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/query': typeof AppQueryRoute
  '/app/upload': typeof AppUploadRoute
  '/app/anomalies/$id': typeof AppAnomaliesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/app/anomalies': typeof AppAnomaliesRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/query': typeof AppQueryRoute
  '/app/upload': typeof AppUploadRoute
  '/app/anomalies/$id': typeof AppAnomaliesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/app/anomalies': typeof AppAnomaliesRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/query': typeof AppQueryRoute
  '/app/upload': typeof AppUploadRoute
  '/app/anomalies/$id': typeof AppAnomaliesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/docs'
    | '/features'
    | '/app/anomalies'
    | '/app/dashboard'
    | '/app/query'
    | '/app/upload'
    | '/app/anomalies/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/docs'
    | '/features'
    | '/app/anomalies'
    | '/app/dashboard'
    | '/app/query'
    | '/app/upload'
    | '/app/anomalies/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/docs'
    | '/features'
    | '/app/anomalies'
    | '/app/dashboard'
    | '/app/query'
    | '/app/upload'
    | '/app/anomalies/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/query': {
      id: '/app/query'
      path: '/query'
      fullPath: '/app/query'
      preLoaderRoute: typeof AppQueryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/anomalies': {
      id: '/app/anomalies'
      path: '/anomalies'
      fullPath: '/app/anomalies'
      preLoaderRoute: typeof AppAnomaliesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/anomalies/$id': {
      id: '/app/anomalies/$id'
      path: '/$id'
      fullPath: '/app/anomalies/$id'
      preLoaderRoute: typeof AppAnomaliesIdRouteImport
      parentRoute: typeof AppAnomaliesRoute
    }
  }
}

interface AppAnomaliesRouteChildren {
  AppAnomaliesIdRoute: typeof AppAnomaliesIdRoute
}

const AppAnomaliesRouteChildren: AppAnomaliesRouteChildren = {
  AppAnomaliesIdRoute: AppAnomaliesIdRoute,
}

const AppAnomaliesRouteWithChildren = AppAnomaliesRoute._addFileChildren(
  AppAnomaliesRouteChildren,
)

interface AppRouteChildren {
  AppAnomaliesRoute: typeof AppAnomaliesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppQueryRoute: typeof AppQueryRoute
  AppUploadRoute: typeof AppUploadRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnomaliesRoute: AppAnomaliesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppQueryRoute: AppQueryRoute,
  AppUploadRoute: AppUploadRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
